services:
  importer:
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.13-slim
        RUN mkdir /app
        WORKDIR /app
        RUN pip install uv
        COPY pyproject.toml .
        RUN uv sync
        COPY . .
        CMD ["uv", "--verbose", "run", "python", "import_prices_to_influx.py", "--loop"]
    container_name: importer
    environment:
      - YEAR=2026
      - BZN=PL
      - INFLUX_URL=http://192.168.1.58:8086
      - INFLUX_TOKEN=WffsS4-GvyrMXUXzwumsTzAYxNr4Lrt1Y4-e7yxrjfseIIrexMdbl7HnkQ2rJ-rkYG2n-ewWYra8rTQU1WVM3Q==
      - INFLUX_ORG=home
      - INFLUX_BUCKET=prices
    restart: unless-stopped
