services:
  importer:
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.13-slim
        RUN mkdir /app
        WORKDIR /app
        RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
        RUN pip install uv
        RUN curl -o pyproject.toml https://raw.githubusercontent.com/btaczala/energy-charts-influxdb/refs/heads/main/pyproject.toml
        RUN uv sync
        RUN curl -o import_prices_to_influx.py https://raw.githubusercontent.com/btaczala/energy-charts-influxdb/refs/heads/main/import_prices_to_influx.py
        RUN curl -o energy_prices_script.py https://raw.githubusercontent.com/btaczala/energy-charts-influxdb/refs/heads/main/energy_prices_script.py
        CMD ["uv", "--verbose", "run", "python", "import_prices_to_influx.py", "--loop"]
    container_name: importer
    environment:
      - YEAR=2026
      - BZN=PL
      - INFLUX_URL=YOUR_URL
      - INFLUX_ORG=YOUR_ORG
      - INFLUX_BUCKET=YOUR_BUCKET
      - INFLUX_TOKEN=YOUR_TOKEN
    restart: unless-stopped
